### ISSUE TITLE
Add the option to reset / reuse a poll

### ISSUE THREAD

**Issue by LorianColtof** [wjclub/telegram-bot-groupagree#2]
I use the exact same poll almost every day, and I have to recreate it every time.
It would be nice to be able to reuse a single poll by clearing the votes.

**Comment by browny99** [comment]
@LorianColtof Noted
We might implement this as a clone rather than a reset but it's added to the To-Do List

**Comment by LorianColtof** [comment]
Yes, I also think that cloning is actually a nicer solution.

**Comment by browny99** [comment]
@LorianColtof Await it in @reallyunstablegroupagreebot

**Comment by browny99** [comment]
Okay the work is done, I'll deploy it in the next hour

**Comment by browny99** [comment]
@browny99 Implemented

**Comment by MaicoTimmerman** [comment]
When will this become available in @groupagreebot?

**Comment by browny99** [comment]
@MaicoTimmerman ETA son

**Comment by MaicoTimmerman** [comment]
Bump

**Comment by jfowl** [comment]
@MaicoTimmerman Have a look at @reallyunstablegroupagreebot
