### ISSUE TITLE
Doesn't respond when "$USERNAME" is in vote option

### ISSUE THREAD

**Issue by DzyubSpirit** [wjclub/telegram-bot-groupagree#4]
The bot stops responding when you write "$USERNAME" or some string with "$USERNAME" in it in vote option. However, $W and $USERNAMEW works perfectly.

**Comment by browny99** [comment]
Thank you for reporting this. I have tested it myself and the bot indeed stops and throws an error when you add this to the vote options. I will investigate this issue, join @groupagreebotdevelopment for the progress and to help us figure out exactly what is wrong

**Comment by browny99** [comment]
This is due to a change in the way Telegram encodes entities. This is fixed in the newest development version, but not in the repo yet.
