### ISSUE TITLE
SQL Errors - DB layout?

### ISSUE THREAD

**Issue by JayDeesSpace** [wjclub/telegram-bot-groupagree#5]
After compiling and setting everything up running on docker at a linux host I ended up getting the error within the app container:

>  Getting updates...
> Error writing request: The authentication or decryption has failed.

This should be a database issue because I couldn't import the temporary db layout script because the link in the readme file isn't working. The database is available and I'm able to connect from the app-container but even with help of the exception I don't get further information, so the problem should be the missing tables and columns.
I tried creating tables and columns using the sourcecode but I'm sure there's something missing.. :)

**Comment by browny99** [comment]
Sorry for the long wait I finally got around to uploading that file.
