### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by rentalhost** [wjclub/telegram-bot-groupagree#7]
I know that here is not the right place, but I can't found another contact method. The bot is not working (none of the instances), and I really need it :D 

Additionally, how many replies I can add to a single poll?

**Comment by vrumger** [comment]
@rentalhost You can ask that in https://t.me/wjclubchat

**Comment by browny99** [comment]
Working on it now

**Comment by browny99** [comment]
Fixed...
https://github.com/wjclub/groupagree-watcher/commit/da607575cf392d32340b6060e42ee881e72f4d3b
